import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AppHeader from "@/containers/AppHeader";
import AppFooter from "@/containers/AppFooter";
import { LocaleProvider, Locale } from "@/i18n";
import { getDictionary } from "@/i18n/server/getDictionary";

import "normalize.css/normalize.css";
import "instantsearch.css/themes/satellite-min.css";
import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = params;
  const dictionary = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <LocaleProvider locale={locale} dictionary={dictionary}>
          <AppHeader />
          {children}
          <AppFooter />
        </LocaleProvider>
      </body>
    </html>
  );
}
